### ISSUE TITLE
build script hangs on the lambda-image branch

### ISSUE THREAD

**Issue by matt-alion** [sutt0n/serverless-clamav-lambda-layer#1]
Thanks for the work you've put into this!  Just wanted to point out I tried to deploy the ClamAV solution that puts the docker container in ECR, and it's just hanging when the lambda entry bootstrap script tries to run handler.js.

```
Step 47/50 : FROM public.ecr.aws/lambda/nodejs:14
 ---> cc19bb2c4fd7
Step 48/50 : COPY --from=layer-image /home/build ./
 ---> fbe8b26f95fa
Step 49/50 : COPY handler.js ./
 ---> 2f43f7f6a70a
Step 50/50 : CMD ["handler.virusScan"]
 ---> Running in 008fa0d5f9db
Removing intermediate container 008fa0d5f9db
 ---> 91f355b901a7
Successfully built 91f355b901a7
Successfully tagged clamav:latest
07 Apr 2022 14:57:22,789 [INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)
```

**Comment by sutt0n** [comment]
@matt-alion:

Sorry about the late reply; I'm addressing fixes on both the `master` branch and the `lambda-image` branch. Seems I overlooked some things on the `build.sh` script, because it's running it immediately after it's built. Since it's all contained in the Docker image, there's no need to try to do any binary shenanigans involving a ZIP file.

Thanks for bringing this up! I'll have a fix out shortly.

**Comment by sutt0n** [comment]
@matt-alion:

Should be addressed in https://github.com/sutt0n/serverless-clamav-lambda-layer/commit/b71ef4f54b42ddadf2ffc753f08ab74d7ce0cb5c

Let me know if that update to the `lambda-image` works -- note that I've updated the roles and such. I'll also verify it on the `master` branch.

**Comment by matt-alion** [comment]
Thanks @sutt0n!

I've got guard rails in my environment that I have to use existing roles, but I tailored the serverless.yml to my situation. The rest works great!

**Comment by sutt0n** [comment]
@matt-alion Great to hear, thanks for the update! Let me know if you have anymore problems.
